Some differences in the list of symbol in the binary causes the Debian symbol
check for ABI changes to fail.
<br /><br />
For example, this has been reported with a test case in upstream bug: <a href="https://llvm.org/bugs/show_bug.cgi?id=30441">https://llvm.org/bugs/show_bug.cgi?id=30441</a> (fixed now)<br />
or <a href="https://bugs.llvm.org/show_bug.cgi?id=45322">https://bugs.llvm.org/show_bug.cgi?id=45322<a/>
<!--
<pre class="failure">

</pre>
-->
